
#pragma once
#include "gRF.h"

class Data_Sample2 : public Data
{
public:

	// the meaningful feature value, provided when a, b and c are all below 0.2
	featuretype x;
	// ground truth label
	labeltype l;

	Data_Sample2();

	// extract features
	// index: one Data class object could contain N samples, and index indicates which sample to extract feature from. In this sample program N=1 thus index is not useful
	// abc: the feature extracting parameters, randomly generated by RandomABC() in Function class
	// feature_out (output): extracted features of D dimensions should be output here. In this sample program D=1
	// ei: used internaly, so ignore it
	virtual void GetFeature(int index, featuretype* abc, featuretype* feature_out, int* ei);
	
	// provide ground truth label
	virtual void GetLabel(int index, labeltype* label_out, int* ei);
};