
#pragma once
#include "gRF.h"

class Data_Sample2 : public Data
{
public:

	// the meaningful feature value, provided when a, b and c are all below 0.1
	float x;
	// ground truth target value
	float v;

	Data_Sample2();

	// extract features
	// index: one Data class object could contain N samples, and index indicates which sample to extract feature from. In this sample program N=1 thus index is not useful
	// abc: the feature extracting parameters, usually randomly generated by RandomABC() in Function class
	// feature_out (output): extracted features of D dimensions should be output here. In this sample program D=1
	// ei: used internaly, so ignore it
	virtual void GetFeature(int index, featuretype* abc, featuretype* feature_out, int* ei);
	
	// provide target value
	virtual void GetValue(int index, valuetype* value_out, int* ei);
};